name: Deploy to gh-page
permissions:
  contents: write
on:
  push:
    branches: master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v2

      - name: CI
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Prettier
        run: npm run prettier
      
      - name: Lint
        run: npm run lint

      - name: Jest
        run: npm run jest

      - name: Run build
        run: npm run build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist          